/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class AllStringUI extends Scene {
		public label:Laya.Label;
		public textinput:Laya.TextInput;
		public htmlStr:Laya.HTMLDivElement;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("AllString");
        }
    }
    REG("ui.AllStringUI",AllStringUI);
    export class AnimUI extends Scene {
		public move:Laya.FrameAnimation;
		public roleAnim:Laya.Animation;
		public ui:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("Anim");
        }
    }
    REG("ui.AnimUI",AnimUI);
    export class buttonUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("button");
        }
    }
    REG("ui.buttonUI",buttonUI);
    export class checkBoxUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("checkBox");
        }
    }
    REG("ui.checkBoxUI",checkBoxUI);
    export class clipUI extends Scene {
		public start:Laya.Button;
		public numClip:Laya.Clip;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("clip");
        }
    }
    REG("ui.clipUI",clipUI);
    export class comboBoxUI extends Scene {
		public comboBoxNode:Laya.ComboBox;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("comboBox");
        }
    }
    REG("ui.comboBoxUI",comboBoxUI);
    export class HSliderUI extends Scene {
		public hsliderNode:Laya.HSlider;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("HSlider");
        }
    }
    REG("ui.HSliderUI",HSliderUI);
    export class labelTxtUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("labelTxt");
        }
    }
    REG("ui.labelTxtUI",labelTxtUI);
    export class listUI extends Scene {
		public list:Laya.List;
		public item:Laya.Label;
		public btn:Laya.Button;
		public refresh:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("list");
        }
    }
    REG("ui.listUI",listUI);
    export class progressUI extends Scene {
		public progressNode:Laya.ProgressBar;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("progress");
        }
    }
    REG("ui.progressUI",progressUI);
    export class RadioGroupUI extends Scene {
		public radioGroupNode:Laya.RadioGroup;
		public cutomRadioGroup:Laya.RadioGroup;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("RadioGroup");
        }
    }
    REG("ui.RadioGroupUI",RadioGroupUI);
    export class spineUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("spine");
        }
    }
    REG("ui.spineUI",spineUI);
    export class tabUI extends Scene {
		public tabNode:Laya.Tab;
		public cutomTab:Laya.Tab;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("tab");
        }
    }
    REG("ui.tabUI",tabUI);
    export class tweenUI extends Scene {
		public l1:Laya.Text;
		public a0:Laya.Text;
		public y1:Laya.Text;
		public a1:Laya.Text;
		public b1:Laya.Text;
		public o1:Laya.Text;
		public x1:Laya.Text;
		public startAction:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("tween");
        }
    }
    REG("ui.tweenUI",tweenUI);
    export class VSliderUI extends Scene {
		public vsliderNode:Laya.VSlider;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("VSlider");
        }
    }
    REG("ui.VSliderUI",VSliderUI);
    export class xlzdhUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("xlzdh");
        }
    }
    REG("ui.xlzdhUI",xlzdhUI);
}